### ISSUE TITLE
@ symbol not properly being converted from UTF8 to GSM

### ISSUE THREAD

**Issue by NatanTechofNY** [BenMorel/GsmCharsetConverter#2]
Having issues with the @ symbol being converted to a blank string from UTF8 to GSM.

**Comment by BenMorel** [comment]
From what I can see in the [charset table](https://github.com/BenMorel/GsmCharsetConverter/blob/master/src/Charset.php#L26), `@` in UTF-8 maps to ASCII `00` (null byte) in the GSM charset, this is a non-printable character in other charsets, and probably what you interpret as a blank string.

Feel free to comment if I misunderstood.

**Comment by NatanTechofNY** [comment]
@BenMorel for some reason when you do `utf8_decode()` on a string that contains the `@` character and send it as an SMS, it sends it as GSM and the `@` can be seen in the message. Is there something I am missing here?

**Comment by BenMorel** [comment]
There are too many possible issues here. If you're using `utf8_decode()`, you end up with a `iso-8859-1` string. When you say "send it as an SMS", it can mean many different things, this all depends on what your SMS gateway accepts as input encoding.

Most of the modern gateways do not take a GSM charset string as input directly, instead they typically accept `iso-8859-1` or `UTF-8` as input, and handle the low-level conversion for you.

Where this library may be useful to you, is to enforce sending SMS messages in the GSM charset (160 chars / message) instead of UCS-2 (70 chars per message) to save on sending costs, if your gateway does not offer this option. This is achieved by using `cleanUpUtf8String()`: this way, you're still sending UTF-8, but you are guaranteed that this UTF-8 string only contains characters that can be safely converted to the GSM charset, and that the gateway won't fall back to UCS-2 and double your costs because of a single unsupported accented char or emoji.

If your gateway accepts `iso-8859-1` (latin1) only, you may be able to get away with `utf8_decode(cleanUpUtf8String(...))`.
